### ISSUE TITLE
New Iteration Style Breaks Highlighting

### ISSUE THREAD

**Issue by spinlock99** [yalesov/vim-emblem#12]
With the old style `each` iterator, functions were highlighted like this (note the class binding):

![screen shot 2015-04-27 at 1 56 01 pm](https://cloud.githubusercontent.com/assets/453431/7357679/3972e1b4-ece5-11e4-834c-53ec085b3150.png)

However, the new `each todo in model` style breaks this highlighting:

![screen shot 2015-04-27 at 1 55 11 pm](https://cloud.githubusercontent.com/assets/453431/7357719/6f0af53c-ece5-11e4-94d6-aff7bb2e8fbc.png)

**Comment by ballPointPenguin** [comment]
Related: 
new bracketed attributes style breaks highlighting.
see https://github.com/machty/emblem.js/commit/e1a94ed9bae550d61f766255d8a0010f19f04c5b

**Comment by yalesov** [comment]
This particular issue has been isolated to a _syntax error_ .

![screenshot from 2016-07-05 05-22-09](https://cloud.githubusercontent.com/assets/20264293/16570028/8c8398a2-4203-11e6-874a-2444dcfc44fd.png)

The `.` (dot) is undefined when used in the `class=todo.isCompleted:completed` context. Assuming you mean `class=todo:isCompleted:completed` (with `:` - colon) though, it's working.

**Comment by yalesov** [comment]
The other two issues (new `each` syntax) and (bracketed attributes) belong to their own threads at #12 and #14.
